# Generated by Django 2.2.7 on 2019-11-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='preordered',
        ),
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.BooleanField(default=False, help_text='Оплата на месте\\ предоплата\\ звонок от менеджера', verbose_name='Способ оплаты'),
        ),
    ]
