# Generated by Django 2.2.7 on 2019-11-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191119_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(help_text='Оплата на месте\\ предоплата\\ звонок от менеджера', max_length=120, verbose_name='Способ оплаты'),
        ),
    ]
