# Generated by Django 2.2.7 on 2019-12-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191203_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StopInRace',
        ),
    ]
