# Generated by Django 2.2.7 on 2019-11-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bus_buscomment_busgood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Question',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
