# Generated by Django 2.2.7 on 2019-11-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191125_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Полное имя'),
        ),
    ]
