# Generated by Django 2.2.7 on 2019-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191206_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
