# Generated by Django 2.2.7 on 2019-12-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191206_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uk',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
