# Generated by Django 2.2.7 on 2019-12-04 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscomment',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.Bus', verbose_name='Автобус'),
        ),
        migrations.AlterField(
            model_name='buscomment',
            name='moderated',
            field=models.BooleanField(default=False, verbose_name='Отображается'),
        ),
        migrations.AlterField(
            model_name='buscomment',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='busgood',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='content.Bus', verbose_name='Автобус'),
        ),
        migrations.AlterField(
            model_name='busgood',
            name='text',
            field=models.TextField(verbose_name='Удобство'),
        ),
    ]
