# Generated by Django 2.2.7 on 2019-12-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busphoto',
            name='photo',
            field=models.ImageField(upload_to='bus_pics/'),
        ),
    ]
