# Generated by Django 3.0.3 on 2020-02-14 17:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191209_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_uk',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
