# Generated by Django 2.2.7 on 2019-12-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20191204_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photoes', to='content.Bus')),
            ],
            options={
                'verbose_name': 'Фотография автобуса',
                'verbose_name_plural': 'Фотографии автобусов',
            },
        ),
    ]
