# Generated by Django 2.2.7 on 2019-12-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_busphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='busphoto',
            name='alt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
