# Generated by Django 2.2.7 on 2019-12-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_busphoto_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_uk',
        ),
    ]
