# Generated by Django 2.2.7 on 2019-12-03 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('comment', models.TextField(verbose_name='Вопрос')),
                ('peoples', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ Микроавтобуса',
                'verbose_name_plural': 'Заказ Микроавтобуса',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Вопрос')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='EuropeContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('comment', models.TextField(verbose_name='Вопрос')),
                ('peoples', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ поездки в Европу',
                'verbose_name_plural': 'Заказ поездки в Европу',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Полное имя')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емайл')),
                ('departion', models.CharField(blank=True, max_length=120, null=True, verbose_name='Город отправления')),
                ('arrival', models.CharField(blank=True, max_length=120, null=True, verbose_name='Город прибытия')),
                ('sk', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('ordered', models.BooleanField(default=False, verbose_name='завершен')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/', verbose_name='Билет')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлен')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.Race', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_card_mask2', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_card_bank', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_card_type', models.CharField(blank=True, max_length=120, null=True)),
                ('sender_card_country', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплата',
            },
        ),
    ]
